### ISSUE TITLE
Question about GAMS

### ISSUE THREAD

**Issue by xuzs9298** [xuzs9298/CGEpy#6]
# CHEQ(I,H).. CH(I,H)=E= CH0(I,H) * ( ( YD(H)  / YD0(H)  ) / ( CPI(H) / CPI0(H) ) ) ** (BETA(I,H)*1.0)
#                        * PROD(J, ( ( P(J)*TT(I)  * ( 1 + SUM(GS, TAUC(GS,J) ) ) ) / ( P0(J) * ( 1 + SUM(GS, TAUQ(GS,J) ) ) ) )** (LAMBDA(J,I)*1) ) ;

Two questions about this equation:

1. What is "PROD" ? I believe is the same with "SUM" but get the product instead. 

2. I think P(J)*TT(I) should create a 2-d matrix with rows J and cols I, otherwise, it doesn't match with the size of LAMBDA(J,I). 

Can you confirm whether my assumption is correct, Russ?

**Comment by russbramblett** [comment]
1. Yes
2. Because "I" and "J" are the transpose of each other, I believe you are correct. I'm not sure what TT(I) is, though. It is set to 1 and isn't a variable. I looked through a couple of other GAMS files and the equations are written without TT(I) in them. It looks like it could be a scaler for each industry... but it isn't used. Odd.

**Comment by xuzs9298** [comment]
Thanks.
